# Generated by Django 5.1 on 2024-08-24 20:09

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_code_course_course_code_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='course_code',
            field=models.CharField(default=334242423, max_length=10, unique=True, verbose_name=courses.models.Course),
            preserve_default=False,
        ),
    ]
